version: "2"
services:
  web:
    image: "magic-box/web"
    ports:
      - "80:80"
    depends_on:
      - db
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  db:
    restart: "always"
    image: "magic-box/db"
    ports:
      - "5432:5432"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  music:
    image: "magic-box/music"
    ports: 
      - "8081:8081"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  prompts:
    image: "magic-box/prompts"
    ports:
      - "8082:8082"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  sprites: 
    image: "magic-box/sprites"
    ports: 
      - "8083:8083"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box
  worlds: 
    image: "magic-box/worlds" 
    ports: 
      - "8084:8084"
    logging:
      driver: awslogs
      options: 
        awslogs-group: magic-box
        awslogs-region: us-east-1
        awslogs-stream-prefix: magic-box